version: "2"
services:
  queues:
    image: rabbitmq:management
    container_name: queues
    ports:
      - "15672:15672"
  send:
    image: send:latest
    container_name: send
    tty: true
    depends_on: 
     - "queues"
  receive:
    image: receive:latest
    container_name: receive
    tty: true
    depends_on: 
     - "queues"

