apiVersion: v1
kind: Pod
metadata:
  name: giantpod
  labels:
    type: stack
spec:
  containers:
  - name: queues
    image: rabbitmq:management
    ports:
    - containerPort: 15672
  - name: send
    image: send:giantpod
    env:
    - name: queues
      value: localhost
  - name: receive
    image: receive:giantpod
    env:
    - name: queues
      value: localhost

# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq
# spec:
#   ports:
#   - port: 15672
#   selector:
#     type: queues
#     service: queues